### ISSUE TITLE
Can not get this installed

### ISSUE THREAD

**Issue by lfiocco** [underbluewaters/homebridge-sainsmart-16-usb#1]
Hello. I was wondering if you can help me with install. I have a sainsmart 16 relay board with the hid type USB_VID = 0x0416; USB_PID = 0x5020.

I installed the command you wrote in the docs, does not work. Are there dependants?

Please help

**Comment by lfiocco** [comment]
Got this installed on Ubuntu, but when I switch on coffee maker nothing happens on relay board

**Comment by underbluewaters** [comment]
Are you seeing any blinking on the relay board where the usb cable is inserted? I've found that this can indicate a "stuck" state and the only way to revive the board is to install [mvines/sainsmart-relay16](https://github.com/mvines/sainsmart-relay16). After running the `sainsmart-relay16 test` command it works again.

**Comment by lfiocco** [comment]
Yes that worked. Thanks for your help. Sometimes I have to reboot the server because I get write errors on the port. Anyway around that?

**Comment by underbluewaters** [comment]
It's probably related to an issue with the underlying library at https://github.com/underbluewaters/sainsmart-16-hid/issues/1. I haven't had a chance to fix it since it's hard to reliable replicate the problem.

**Comment by lfiocco** [comment]
have you tried installing this on raspbian? i keep getting write errors even when i install in sudo.

**Comment by underbluewaters** [comment]
I’m using Raspbian and following these instructions to enable a udev rule:
https://github.com/mvines/sainsmart-relay16#udev-rules
You can ‘tail -f’ syslog while plugging in the usb board to watch and make
sure the rule is enabled.
